image: ubuntu:16.04

before_script:
  - apt-get update
  - apt-get install -y python3 python3-tk build-essential python3-pip nodejs npm curl git
  - npm install -g n
  - n stable
  - cd ..
  - git clone https://github.com/ReNom-dev-team/ReNom.git
  - pip3 install -r ReNom/requirements.txt
  - pip3 install -e ReNom/
  - pip3 install wheel
  - cd ReNomRG
  - pip3 install -r requirements.txt
  - pip3 install -e .

flake8:
  script:
    - flake8 .
