image: ubuntu:16.04

before_script:
  - apt-get update
  - apt-get install -y python3 python3-tk build-essential python3-pip nodejs npm curl git
  - npm install -g n
  - n 10.15.0
  - cd ..
  - pip3 install pytest webtest wheel h5py cython
  - git clone https://github.com/ReNom-dev-team/ReNom.git
  - pip3 install -r ReNom/requirements.txt
  - pip3 install -e ReNom/
  - cd ReNomRG
  - pip3 install -r requirements.txt
  - pip3 install -e .
  - cd js
  - npm install
  - npm run build
  - cd ..

flake8:
  script:
    - flake8 renom_rg
    - pytest

pages:
  script:
    - python3 setup.py bdist_wheel
    - mkdir -p public/bin
    - cp dist/* public/bin
    - ls public/bin

  artifacts:
    paths:
    - public

  # only:
  #   - /^release\/.*$/
  #   - /^v.*beta$/
