"""#42

Revision ID: 1b16a19827b2
Revises: 6f841dee298f
Create Date: 2019-02-19 16:16:34.135974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b16a19827b2'
down_revision = '6f841dee298f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('model_pickle', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'model_pickle')
    # ### end Alembic commands ###
