"""#16

Revision ID: 4e2cc619c7bf
Revises: 37c6da7e0696
Create Date: 2019-02-06 19:30:47.459412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2cc619c7bf'
down_revision = '37c6da7e0696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_def', sa.Column('explanatory_column_ids', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_def', 'explanatory_column_ids')
    # ### end Alembic commands ###
