"""#36

Revision ID: 6f841dee298f
Revises: 4e2cc619c7bf
Create Date: 2019-02-12 11:39:57.247702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f841dee298f'
down_revision = '4e2cc619c7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_def', sa.Column('filename_X', sa.TEXT(), nullable=True))
    op.add_column('dataset_def', sa.Column('filename_y', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_def', 'filename_y')
    op.drop_column('dataset_def', 'filename_X')
    # ### end Alembic commands ###
